version: "3.9"

services:
  php:
    image: ghcr.io/myparcelnl/php-xd:7.2-alpine
    command: [ "sh", "-c", "composer install --no-interaction --no-progress --no-scripts --no-dev --ignore-platform-reqs" ]
    volumes:
      - ./:/app
      - composer-cache:/www-data/.composer/cache
      - /Users/edie/Sites/myparcel/pdk:/Users/edie/Sites/myparcel/pdk

  node:
    image: node:18-alpine
    working_dir: /app
    command: [ "sh", "-c", "yarn && yarn compile" ]
    volumes:
      - ./:/app
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - node-modules:/app/node_modules
      - /Users/edie/Sites/myparcel/pdk-frontend:/Users/edie/Sites/myparcel/pdk-frontend
      - /Users/edie/Sites/vue-form-builder:/Users/edie/Sites/vue-form-builder

volumes:
  composer-cache:
  node-modules:
  yarn-cache:
