##
# Route for the admin page
##
myparcelnl:
  path: myparcelnl
  methods: [GET]
  defaults:
    _controller: 'MyParcelNL\PrestaShop\Controller\AdminController::index'

##
# The controller that executes all PDK actions
##
myparcelnl_pdk:
  path: myparcelnl/pdk
  methods: [ GET, POST, PUT, DELETE ]
  defaults:
    _controller: 'MyParcelNL\PrestaShop\Pdk\Controller\AdminMyParcelPdkController::index'
