name: '⚙️ On pull request'

on:
  pull_request:
    branches:
      - alpha
      - beta

  repository_dispatch:
    types: [trigger-pr-build]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.client_payload.number || github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      ref: ${{ github.event.client_payload.ref || github.ref }}

  build:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}
          persist-credentials: false

      - uses: ./.github/actions/build
        id: build
        with:
          node-version: ${{ vars.NODE_VERSION }}
          php-version: ${{ vars.PHP_VERSION }}
          php-scoper-version: ${{ vars.PHP_SCOPER_VERSION }}

      - name: 'Determine version'
        id: version
        #language=bash
        run: |
          version=$(npm pkg get version | sed 's/"//g') 
          releaseVersion="$version-${{ github.event.client_payload.number || github.event.pull_request.number }}"

          echo "version=$releaseVersion" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/release
        id: release
        with:
          command: 'prerelease'
          image: ${{ steps.build.outputs.image }}
          version: ${{ steps.version.outputs.version }}
