name: '⚙️ On pull request'

on:
  pull_request:
    branches:
      - alpha
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ./.github/actions/build
        id: build
        with:
          node-version: ${{ vars.NODE_VERSION }}
          php-version: ${{ vars.PHP_VERSION }}
          php-scoper-version: ${{ vars.PHP_SCOPER_VERSION }}

      - name: 'Determine version'
        id: version
        #language=bash
        run: |
          version=$(npm pkg get version | sed 's/"//g') 
          releaseVersion="$version-${{ github.event.pull_request.number}}"

          echo "version=$releaseVersion" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/release
        id: release
        with:
          image: ${{ steps.build.outputs.image }}
          version: ${{ steps.version.outputs.version }}
