name: '⚙️ On push'

on:
  push:
    branches:
      - alpha
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./.github/actions/build
        id: build
        with:
          php-scoper-version: ${{ vars.PHP_SCOPER_VERSION }}

      - name: 'Determine version'
        id: version
        #language=sh
        run: |
          version=$(npm pkg get version | sed 's/"//g')
          releaseVersion="$version-${{ github.sha }}"

          echo "version=$releaseVersion" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/release
        id: release
        with:
          image: ${{ steps.build.outputs.image }}
          version: ${{ steps.version.outputs.version }}

  rebase-prs:
    needs:
      - test
    uses: ./.github/workflows/rebase-prs.yml
    secrets: inherit
