name: '⚙️ On push'

on:
  push:
    branches:
      - alpha
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: ./.github/actions/build
        id: build
        with:
          node-version: ${{ vars.NODE_VERSION }}
          php-version: ${{ vars.PHP_VERSION }}
          php-scoper-version: ${{ vars.PHP_SCOPER_VERSION }}

      - name: 'Determine version'
        id: version
        #language=bash
        run: |
          version=$(npm pkg get version | sed 's/"//g')
          commitsSinceTag=$(git log --oneline v$version.. | wc -l)
          releaseVersion="$version-$commitsSinceTag"

          echo "version=$releaseVersion" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/release
        id: release
        with:
          version: ${{ steps.version.outputs.version }}
          image: ${{ steps.build.outputs.image }}

  rebase-prs:
    needs:
      - test
      - build
    uses: ./.github/workflows/rebase-prs.yml
    secrets: inherit
