name: 'Build and publish 🚀'

on:
  push:
    branches:
      - main

  workflow_dispatch: ~

jobs:
  release:
    name: 'Build and publish 🚀'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GH_REPO_TOKEN }}

      # TODO: Switch to v3 with app credentials when GitHub apps are allowed to bypass status checks. https://github.com/orgs/community/discussions/43460
      - uses: myparcelnl/actions/setup-git-credentials@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: myparcelnl/actions/composer-install@v3
        with:
          php-version: '7.4'

      - uses: myparcelnl/actions/yarn-install@v3
        with:
          node-version: '16'

      - uses: myparcelnl/actions/semantic-release@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}

  rebase:
    name: 'Rebase develop onto main'
    uses: ./.github/workflows/rebase.yml
    secrets: inherit
    needs: release
    if: always()
    with:
      base: 'main'
      target: 'develop'

  rebase-prs:
    name: 'Rebase pull requests onto develop'
    needs: rebase
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: peter-evans/rebase@v2
        with:
          token: ${{ steps.credentials.outputs.token }}
          base: develop
          exclude-drafts: true
          exclude-labels: 'hotfix'
